additionalProperties:
  artifactId: aco-ts-sdk
templateDir: templates
files:
  client.mustache:
    templateType: SupportingFiles
    destinationFilename: src/client.ts
  types.mustache:
    templateType: SupportingFiles
    destinationFilename: src/types.ts
  client.test.mustache:
    templateType: SupportingFiles
    destinationFilename: test/unit/client.test.ts
