/**
 * Copyright 2025 Adobe. All Rights Reserved.
 *
 * This file is licensed to you under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, either express or implied. See the License for
 * the specific language governing permissions and limitations under the License.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) using custom templates.
 * Generator configuration can be found in the /generator directory.
 *
 * Do not edit this file manually!
 */

/**
 * Fixed amount discount that reduces the regular price by a specific monetary value. Example: $100 regular price with a
 * $10 fixed discount results in $90 final price.
 *
 * @export
 * @interface DiscountsFinalPrice
 */
export interface DiscountsFinalPrice {
  /**
   * Unique identifier for the discount. Must be unique within the price record. Use descriptive codes for easier
   * management (e.g., "loyalty_discount", "holiday_sale").
   *
   * @memberof DiscountsFinalPrice
   * @type {string}
   */
  code: string;
  /**
   * Fixed discount amount in the same currency as the price book. Must be a positive number less than the regular
   * price.
   *
   * @memberof DiscountsFinalPrice
   * @type {number}
   */
  price: number;
}
/**
 * Percentage discount that reduces the regular price by a specified percentage. Example: $100 regular price with a 20%
 * discount results in $80 final price.
 *
 * @export
 * @interface DiscountsPercentage
 */
export interface DiscountsPercentage {
  /**
   * Unique identifier for the discount. Must be unique within the price record. Use descriptive codes for easier
   * management (e.g., "seasonal_sale", "vip_member").
   *
   * @memberof DiscountsPercentage
   * @type {string}
   */
  code: string;
  /**
   * Discount percentage as a positive number. Valid range is 0.01 to 99.99 (1% to 99.99%).
   *
   * @memberof DiscountsPercentage
   * @type {number}
   */
  percentage: number;
}
/**
 * Category information for organizing products with hierarchical structure and localization support.
 *
 * @export
 * @interface FeedCategory
 */
export interface FeedCategory {
  /**
   * Category slug using hierarchical format with forward slashes to represent parent-child relationships. String can
   * contain only lowercase letters, numbers, and hyphens. Examples: 'men', 'men/clothing', 'men/clothing/pants'
   *
   * @memberof FeedCategory
   * @type {string}
   */
  slug: string;
  /**
   * @memberof FeedCategory
   * @type {Source}
   */
  source: Source;
  /**
   * Display name of the category
   *
   * @memberof FeedCategory
   * @type {string}
   */
  name: string;
  /**
   * Optional array of product family identifiers that this category is associated with. Used for enhanced product
   * organization and filtering.
   *
   * @memberof FeedCategory
   * @type {string[]}
   */
  families?: string[];
}
/**
 * Delete category information for removing categories from the catalog.
 *
 * @export
 * @interface FeedCategoryDelete
 */
export interface FeedCategoryDelete {
  /**
   * Category slug using hierarchical format with forward slashes to represent parent-child relationships. Must use only
   * lowercase letters, numbers, and hyphens. Examples: 'men', 'men/clothing', 'men/clothing/pants'
   *
   * @memberof FeedCategoryDelete
   * @type {string}
   */
  slug: string;
  /**
   * @memberof FeedCategoryDelete
   * @type {Source}
   */
  source: Source;
}
/**
 * Category information for updating existing categories.
 *
 * @export
 * @interface FeedCategoryUpdate
 */
export interface FeedCategoryUpdate {
  /**
   * Category slug using hierarchical format with forward slashes to represent parent-child relationships. String can
   * contain only lowercase letters, numbers, and hyphens. Examples: 'men', 'men/clothing', 'men/clothing/pants'
   *
   * @memberof FeedCategoryUpdate
   * @type {string}
   */
  slug: string;
  /**
   * @memberof FeedCategoryUpdate
   * @type {Source}
   */
  source: Source;
  /**
   * Display name of the category
   *
   * @memberof FeedCategoryUpdate
   * @type {string}
   */
  name?: string;
  /**
   * Optional array of product family identifiers that this category is associated with. Used for enhanced product
   * organization and filtering. For example, for a clothing category, you can associate it with the "apparel" family.
   * Note: This field uses the replace strategy to replace the entire array with the new values.
   *
   * @memberof FeedCategoryUpdate
   * @type {string[]}
   */
  families?: string[];
}
/**
 * @export
 * @interface FeedItemFailedValidationResult
 */
export interface FeedItemFailedValidationResult {
  /**
   * Code name of invalid field.
   *
   * @memberof FeedItemFailedValidationResult
   * @type {string}
   */
  code?: string;
  /**
   * Reference to the line item with an invalid payload. The line count begins at 0.
   *
   * @memberof FeedItemFailedValidationResult
   * @type {number}
   */
  itemIndex?: number;
  /**
   * Error description
   *
   * @memberof FeedItemFailedValidationResult
   * @type {string}
   */
  message?: string;
  /**
   * Original value passed in the request.
   *
   * @memberof FeedItemFailedValidationResult
   * @type {string}
   */
  value?: string;
}
/**
 * Metadata information for a product attribute.
 *
 * @export
 * @interface FeedMetadata
 */
export interface FeedMetadata {
  /**
   * Attribute code
   *
   * @memberof FeedMetadata
   * @type {string}
   */
  code: string;
  /**
   * @memberof FeedMetadata
   * @type {Source}
   */
  source: Source;
  /**
   * Determines how the attribute is used on the storefront. * `PRODUCT_DETAIL`: Product attribute is visible on the
   * Product Detail Page. * `PRODUCT_LISTING`: Product attribute is visible on Product Listing Page. * `SEARCH_RESULTS`:
   * Product attribute is visible on Search Results Page. * `PRODUCT_COMPARE`: Product attribute is visible on Product
   * Compare Page.
   *
   * @memberof FeedMetadata
   * @type {FeedMetadataVisibleInEnum[]}
   */
  visibleIn?: FeedMetadataVisibleInEnum[];
  /**
   * Label for the attribute that is displayed in user interfaces.
   *
   * @memberof FeedMetadata
   * @type {string}
   */
  label: string;
  /**
   * Data type
   *
   * @memberof FeedMetadata
   * @type {FeedMetadataDataTypeEnum}
   */
  dataType: FeedMetadataDataTypeEnum;
  /**
   * Indicates whether the attribute can be used to filter products.
   *
   * @memberof FeedMetadata
   * @type {boolean}
   */
  filterable?: boolean;
  /**
   * Indicates whether the attribute can be used to sort products.
   *
   * @memberof FeedMetadata
   * @type {boolean}
   */
  sortable?: boolean;
  /**
   * Indicates whether the attribute value can be used in search queries to filter results.
   *
   * @memberof FeedMetadata
   * @type {boolean}
   */
  searchable?: boolean;
  /**
   * The weight associated with a searchable attribute. Attributes with a greater weight are returned before attributes
   * with a lower weight.
   *
   * @memberof FeedMetadata
   * @type {number}
   */
  searchWeight?: number;
  /**
   * Search types associated with this attribute, for example: `autocomplete`, `starts_with`, and so on.
   *
   * @memberof FeedMetadata
   * @type {FeedMetadataSearchTypesEnum[]}
   */
  searchTypes?: FeedMetadataSearchTypesEnum[];
}
/**
 * Delete metadata information for a product attribute.
 *
 * @export
 * @interface FeedMetadataDelete
 */
export interface FeedMetadataDelete {
  /**
   * Attribute code
   *
   * @memberof FeedMetadataDelete
   * @type {string}
   */
  code: string;
  /**
   * @memberof FeedMetadataDelete
   * @type {Source}
   */
  source: Source;
}
/**
 * Metadata information for a product attribute.
 *
 * @export
 * @interface FeedMetadataUpdate
 */
export interface FeedMetadataUpdate {
  /**
   * Attribute code
   *
   * @memberof FeedMetadataUpdate
   * @type {string}
   */
  code: string;
  /**
   * @memberof FeedMetadataUpdate
   * @type {Source}
   */
  source: Source;
  /**
   * Determines how the attribute is used on the storefront. * `PRODUCT_DETAIL`: Product attribute is visible on the
   * Product Detail Page. * `PRODUCT_LISTING`: Product attribute is visible on Product Listing Page. * `SEARCH_RESULTS`:
   * Product attribute is visible on Search Results Page. * `PRODUCT_COMPARE`: Product attribute is visible on Product
   * Compare Page.
   *
   * @memberof FeedMetadataUpdate
   * @type {FeedMetadataUpdateVisibleInEnum[]}
   */
  visibleIn?: FeedMetadataUpdateVisibleInEnum[];
  /**
   * Label for the attribute that is displayed in user interfaces.
   *
   * @memberof FeedMetadataUpdate
   * @type {string}
   */
  label?: string;
  /**
   * Data type
   *
   * @memberof FeedMetadataUpdate
   * @type {FeedMetadataUpdateDataTypeEnum}
   */
  dataType?: FeedMetadataUpdateDataTypeEnum;
  /**
   * Indicates whether the attribute can be used to filter products.
   *
   * @memberof FeedMetadataUpdate
   * @type {boolean}
   */
  filterable?: boolean;
  /**
   * Indicates whether the attribute can be used to sort products.
   *
   * @memberof FeedMetadataUpdate
   * @type {boolean}
   */
  sortable?: boolean;
  /**
   * Indicates whether the attribute value can be used in search queries to filter results.
   *
   * @memberof FeedMetadataUpdate
   * @type {boolean}
   */
  searchable?: boolean;
  /**
   * The weight associated with a searchable attribute. Attributes with a greater weight are returned before attributes
   * with a lower weight.
   *
   * @memberof FeedMetadataUpdate
   * @type {number}
   */
  searchWeight?: number;
  /**
   * Search types associated with this attribute, for example: `autocomplete`, `starts_with`, and so on.
   *
   * @memberof FeedMetadataUpdate
   * @type {FeedMetadataUpdateSearchTypesEnum[]}
   */
  searchTypes?: FeedMetadataUpdateSearchTypesEnum[];
}
/**
 * Price book information
 *
 * @export
 * @interface FeedPriceBookDelete
 */
export interface FeedPriceBookDelete {
  /**
   * Price book id
   *
   * @memberof FeedPriceBookDelete
   * @type {string}
   */
  priceBookId: string;
}
/**
 * Price book information supporting hierarchical pricing structures. Use base price books to define currency and create
 * child price books for specific pricing scenarios.
 *
 * @type FeedPricebook
 * @export
 */
export type FeedPricebook = PriceBookBase | PriceBookChild;
/**
 * Product price information with support for regular pricing, discounts, and tiered pricing. Each price record must
 * reference an existing price book and can include multiple discount types and tiered pricing levels for different
 * quantity thresholds.
 *
 * @export
 * @interface FeedPrices
 */
export interface FeedPrices {
  /**
   * Product SKU identifier. Must match an existing product in the catalog. For configurable products, use the variant
   * SKU, not the parent SKU.
   *
   * @memberof FeedPrices
   * @type {string}
   */
  sku: string;
  /**
   * Price book identifier. Must reference an existing price book. Prices referencing non-existing price books are
   * ignored.
   *
   * @memberof FeedPrices
   * @type {string}
   */
  priceBookId: string;
  /**
   * Base price for the product SKU in the specified price book. This is the price before any discounts or tiered
   * pricing are applied.
   *
   * @memberof FeedPrices
   * @type {number}
   */
  regular: number;
  /**
   * Array of active discounts applied to the regular price. Each discount requires a unique code identifier. Supports
   * both percentage and fixed amount discounts.
   *
   * @memberof FeedPrices
   * @type {FeedPricesDiscountsInner[]}
   */
  discounts?: FeedPricesDiscountsInner[];
  /**
   * Array of tiered pricing for quantity-based discounts. Quantities must be greater than 1. Supports both percentage
   * and fixed price tiers.
   *
   * @memberof FeedPrices
   * @type {FeedPricesTierPricesInner[]}
   */
  tierPrices?: FeedPricesTierPricesInner[];
}
/**
 * Delete product price information.
 *
 * @export
 * @interface FeedPricesDelete
 */
export interface FeedPricesDelete {
  /**
   * Product SKU
   *
   * @memberof FeedPricesDelete
   * @type {string}
   */
  sku: string;
  /**
   * Price book id
   *
   * @memberof FeedPricesDelete
   * @type {string}
   */
  priceBookId: string;
}
/**
 * @type FeedPricesDiscountsInner
 * @export
 */
export type FeedPricesDiscountsInner = DiscountsFinalPrice | DiscountsPercentage;
/**
 * @type FeedPricesTierPricesInner
 * @export
 */
export type FeedPricesTierPricesInner = TierFinalPrice | TierPercentage;
/**
 * Product price information.
 *
 * @export
 * @interface FeedPricesUpdate
 */
export interface FeedPricesUpdate {
  /**
   * Product SKU
   *
   * @memberof FeedPricesUpdate
   * @type {string}
   */
  sku: string;
  /**
   * Price book id
   *
   * @memberof FeedPricesUpdate
   * @type {string}
   */
  priceBookId: string;
  /**
   * Regular price
   *
   * @memberof FeedPricesUpdate
   * @type {number}
   */
  regular?: number;
  /**
   * Active discounts
   *
   * @memberof FeedPricesUpdate
   * @type {FeedPricesDiscountsInner[]}
   */
  discounts?: FeedPricesDiscountsInner[];
  /**
   * Tier prices for quantities greater-than one
   *
   * @memberof FeedPricesUpdate
   * @type {FeedPricesTierPricesInner[]}
   */
  tierPrices?: FeedPricesTierPricesInner[];
}
/**
 * @export
 * @interface FeedProduct
 */
export interface FeedProduct {
  /**
   * SKU (Stock Keeping Unit) is a unique identifier for a product.
   *
   * @memberof FeedProduct
   * @type {string}
   */
  sku: string;
  /**
   * @memberof FeedProduct
   * @type {Source}
   */
  source: Source;
  /**
   * Product name
   *
   * @memberof FeedProduct
   * @type {string}
   */
  name: string;
  /**
   * The URL key for the product.
   *
   * @memberof FeedProduct
   * @type {string}
   */
  slug: string;
  /**
   * The main description for the product
   *
   * @memberof FeedProduct
   * @type {string}
   */
  description?: string;
  /**
   * A short description of the product
   *
   * @memberof FeedProduct
   * @type {string}
   */
  shortDescription?: string;
  /**
   * Indicates whether the product is visible on the storefront. The value is "Enabled" if it is visible, and "Disabled"
   * if it is not visible.
   *
   * @memberof FeedProduct
   * @type {FeedProductStatusEnum}
   */
  status: FeedProductStatusEnum;
  /**
   * Storefront area where the product is visible. An empty list means that it is not visible as a stand alone product.
   *
   * - `CATALOG`: Product is visible on Product Listing Page and Product Detail Page. * `SEARCH`: Product is visible on
   *   Search Results Page and Product Detail Page.
   *
   * @memberof FeedProduct
   * @type {FeedProductVisibleInEnum[]}
   */
  visibleIn?: FeedProductVisibleInEnum[];
  /**
   * @memberof FeedProduct
   * @type {ProductMetaAttribute}
   */
  metaTags?: ProductMetaAttribute;
  /**
   * A list of product attributes.
   *
   * @memberof FeedProduct
   * @type {ProductAttribute[]}
   */
  attributes?: ProductAttribute[];
  /**
   * A list of product images.
   *
   * @memberof FeedProduct
   * @type {ProductImage[]}
   */
  images?: ProductImage[];
  /**
   * A list of linked SKUs.
   *
   * @memberof FeedProduct
   * @type {ProductLink[]}
   */
  links?: ProductLink[];
  /**
   * A list of product routes.
   *
   * @memberof FeedProduct
   * @type {ProductRoutes[]}
   */
  routes?: ProductRoutes[];
  /**
   * Composite products, such as configurable products, must provide a list of product options that a shopper can select
   * (for example, "color", "size", etc.).
   *
   * @memberof FeedProduct
   * @type {ProductConfiguration[]}
   */
  configurations?: ProductConfiguration[];
  /**
   * Composite products, such as bundle products, must include a list of individual products that are part of the
   * bundle, organized into groups (for example, "shirts", "pants", "accessories").
   *
   * @memberof FeedProduct
   * @type {ProductBundle[]}
   */
  bundles?: ProductBundle[];
  /**
   * A list of external IDs for the product.
   *
   * @memberof FeedProduct
   * @type {ProductExternalId[]}
   */
  externalIds?: ProductExternalId[];
}
/**
 * @export
 * @interface FeedProductDelete
 */
export interface FeedProductDelete {
  /**
   * Product unique identifier
   *
   * @memberof FeedProductDelete
   * @type {string}
   */
  sku: string;
  /**
   * @memberof FeedProductDelete
   * @type {Source}
   */
  source: Source;
}
/**
 * @export
 * @interface FeedProductLayer
 */
export interface FeedProductLayer {
  /**
   * SKU (Stock Keeping Unit) that uniquely identifies the base product this layer will modify. Must match an existing
   * product SKU in the catalog.
   *
   * @memberof FeedProductLayer
   * @type {string}
   */
  sku: string;
  /**
   * @memberof FeedProductLayer
   * @type {SourceLayer}
   */
  source: SourceLayer;
  /**
   * Product display name that will override the base product name. Use for localized names, seasonal branding, or
   * promotional titles.
   *
   * @memberof FeedProductLayer
   * @type {string}
   */
  name?: string;
  /**
   * URL-friendly identifier for the product page. Override to create layer-specific URLs for SEO or campaign tracking.
   *
   * @memberof FeedProductLayer
   * @type {string}
   */
  slug?: string;
  /**
   * Detailed product description that replaces the base product description. Use for localized content, seasonal
   * messaging, or enhanced marketing copy.
   *
   * @memberof FeedProductLayer
   * @type {string}
   */
  description?: string;
  /**
   * Brief product summary that appears in product listings and search results. Override for concise, layer-specific
   * messaging.
   *
   * @memberof FeedProductLayer
   * @type {string}
   */
  shortDescription?: string;
  /**
   * @memberof FeedProductLayer
   * @type {ProductMetaAttribute}
   */
  metaTags?: ProductMetaAttribute;
  /**
   * Product attributes that will be merged with base product attributes. Use to add layer-specific variants, localized
   * values, or seasonal properties.
   *
   * @memberof FeedProductLayer
   * @type {ProductAttribute[]}
   */
  attributes?: ProductAttribute[];
  /**
   * Product images that will be merged with base product images. Use to add seasonal imagery, locale-specific photos,
   * or promotional visuals.
   *
   * @memberof FeedProductLayer
   * @type {ProductImage[]}
   */
  images?: ProductImage[];
  /**
   * Related product SKUs that will be merged with base product links. Use to add seasonal recommendations,
   * locale-specific cross-sells, or promotional bundles.
   *
   * @memberof FeedProductLayer
   * @type {ProductLink[]}
   */
  links?: ProductLink[];
  /**
   * URL routing configurations that will be merged with base product routes. Use to add layer-specific navigation paths
   * or campaign-specific URLs.
   *
   * @memberof FeedProductLayer
   * @type {ProductRoutes[]}
   */
  routes?: ProductRoutes[];
  /**
   * Product configuration options for composite products (for example, configurable products) that will be merged with
   * base configurations. Use to add layer-specific variants or seasonal options.
   *
   * @memberof FeedProductLayer
   * @type {ProductConfiguration[]}
   */
  configurations?: ProductConfiguration[];
  /**
   * Bundle product definitions that will be merged with base product bundles. Use to create seasonal bundles,
   * promotional packages, or locale-specific product groupings.
   *
   * @memberof FeedProductLayer
   * @type {ProductBundle[]}
   */
  bundles?: ProductBundle[];
  /**
   * External system identifiers that will be merged with base product external IDs. Use to add layer-specific tracking
   * codes, campaign IDs, or integration references.
   *
   * @memberof FeedProductLayer
   * @type {ProductExternalId[]}
   */
  externalIds?: ProductExternalId[];
}
/**
 * @export
 * @interface FeedProductLayerDelete
 */
export interface FeedProductLayerDelete {
  /**
   * SKU (Stock Keeping Unit) that identifies the base product containing the layer to delete. Must match an existing
   * product SKU in the catalog.
   *
   * @memberof FeedProductLayerDelete
   * @type {string}
   */
  sku: string;
  /**
   * @memberof FeedProductLayerDelete
   * @type {SourceLayer}
   */
  source: SourceLayer;
}
/**
 * @export
 * @interface FeedProductUpdate
 */
export interface FeedProductUpdate {
  /**
   * SKU (Stock Keeping Unit) is a unique identifier for a product.
   *
   * @memberof FeedProductUpdate
   * @type {string}
   */
  sku: string;
  /**
   * @memberof FeedProductUpdate
   * @type {Source}
   */
  source: Source;
  /**
   * Product name
   *
   * @memberof FeedProductUpdate
   * @type {string}
   */
  name?: string;
  /**
   * The URL key for the product.
   *
   * @memberof FeedProductUpdate
   * @type {string}
   */
  slug?: string;
  /**
   * The main description for the product
   *
   * @memberof FeedProductUpdate
   * @type {string}
   */
  description?: string;
  /**
   * A short description of the product
   *
   * @memberof FeedProductUpdate
   * @type {string}
   */
  shortDescription?: string;
  /**
   * Indicates whether the product is visible on the storefront. The value is "Enabled" if it is visible, and "Disabled"
   * if it is not visible.
   *
   * @memberof FeedProductUpdate
   * @type {FeedProductUpdateStatusEnum}
   */
  status?: FeedProductUpdateStatusEnum;
  /**
   * Storefront area where the product is visible. An empty list means that it is not visible as a stand alone product.
   *
   * - `CATALOG`: Product is visible on Product Listing Page and Product Detail Page. * `SEARCH`: Product is visible on
   *   Search Results Page and Product Detail Page.
   *
   * @memberof FeedProductUpdate
   * @type {FeedProductUpdateVisibleInEnum[]}
   */
  visibleIn?: FeedProductUpdateVisibleInEnum[];
  /**
   * @memberof FeedProductUpdate
   * @type {ProductMetaAttribute}
   */
  metaTags?: ProductMetaAttribute;
  /**
   * A list of product attributes.
   *
   * @memberof FeedProductUpdate
   * @type {ProductAttribute[]}
   */
  attributes?: ProductAttribute[];
  /**
   * A list of product images.
   *
   * @memberof FeedProductUpdate
   * @type {ProductImage[]}
   */
  images?: ProductImage[];
  /**
   * A list of linked SKUs. For product variants, this is a required field that establishes a link between a product
   * variant and the corresponding configurable product. `VARIANT_OF` link type must be specified to establish a
   * connection to the configurable product SKU.
   *
   * @memberof FeedProductUpdate
   * @type {ProductLink[]}
   */
  links?: ProductLink[];
  /**
   * A list of product routes.
   *
   * @memberof FeedProductUpdate
   * @type {ProductRoutes[]}
   */
  routes?: ProductRoutes[];
  /**
   * Composite products, such as configurable products, must provide a list of product options that a shopper can select
   * (for example, "color", "size", etc.).
   *
   * @memberof FeedProductUpdate
   * @type {ProductConfiguration[]}
   */
  configurations?: ProductConfiguration[];
  /**
   * Composite products, such as bundle products, must include a list of individual products that are part of the
   * bundle, organized into groups (for example, "shirts", "pants", "accessories").
   *
   * @memberof FeedProductUpdate
   * @type {ProductBundle[]}
   */
  bundles?: ProductBundle[];
  /**
   * A list of external IDs for the product.
   *
   * @memberof FeedProductUpdate
   * @type {ProductExternalId[]}
   */
  externalIds?: ProductExternalId[];
}
/**
 * @export
 * @interface Model400ProcessFeedResponse
 */
export interface Model400ProcessFeedResponse {
  /**
   * Request status.
   *
   * @memberof Model400ProcessFeedResponse
   * @type {string}
   */
  status?: string;
  /**
   * Error summary.
   *
   * @memberof Model400ProcessFeedResponse
   * @type {string}
   */
  message?: string;
  /**
   * List of items that did not pass validation. Fix the payload for invalid items before resubmitting the request.
   *
   * @memberof Model400ProcessFeedResponse
   * @type {FeedItemFailedValidationResult[]}
   */
  errors?: FeedItemFailedValidationResult[];
}
/**
 * @export
 * @interface Model401Response
 */
export interface Model401Response {
  /**
   * Error title
   *
   * @memberof Model401Response
   * @type {string}
   */
  title?: string;
  /**
   * Error status code
   *
   * @memberof Model401Response
   * @type {string}
   */
  status?: string;
  /**
   * Error code
   *
   * @memberof Model401Response
   * @type {string}
   */
  errorCode?: string;
  /**
   * Error message
   *
   * @memberof Model401Response
   * @type {string}
   */
  message?: string;
}
/**
 * @export
 * @interface Model403Response
 */
export interface Model403Response {
  /**
   * Error title
   *
   * @memberof Model403Response
   * @type {string}
   */
  title?: string;
  /**
   * Error status code
   *
   * @memberof Model403Response
   * @type {string}
   */
  status?: string;
  /**
   * Error code
   *
   * @memberof Model403Response
   * @type {string}
   */
  errorCode?: string;
  /**
   * Error message
   *
   * @memberof Model403Response
   * @type {string}
   */
  message?: string;
}
/**
 * @export
 * @interface PriceBookBase
 */
export interface PriceBookBase {
  /**
   * Unique identifier for the base price book. Must be unique across all price books. Used to reference this price book
   * in child price books and pricing data.
   *
   * @memberof PriceBookBase
   * @type {string}
   */
  priceBookId: string;
  /**
   * Human-readable name for the price book. Used for display and identification purposes.
   *
   * @memberof PriceBookBase
   * @type {string}
   */
  name: string;
  /**
   * Currency code that applies to this price book and all its child price books in ISO format. Child price books
   * inherit this currency and cannot override it.
   *
   * @memberof PriceBookBase
   * @type {string}
   */
  currency: string;
}
/**
 * Nested price book that inherits currency from its parent and can extend the pricing hierarchy. Child price books can
 * have up to 3 levels of nesting from the base price book.
 *
 * @export
 * @interface PriceBookChild
 */
export interface PriceBookChild {
  /**
   * Unique identifier for the child price book. Must be unique across all price books. Used to reference this price
   * book in pricing data and potential child price books.
   *
   * @memberof PriceBookChild
   * @type {string}
   */
  priceBookId: string;
  /**
   * Human-readable name for the child price book. Used for display and identification purposes.
   *
   * @memberof PriceBookChild
   * @type {string}
   */
  name: string;
  /**
   * Reference to the parent price book ID. Must reference an existing price book. Determines the currency inheritance
   * and hierarchy level.
   *
   * @memberof PriceBookChild
   * @type {string}
   */
  parentId: string;
}
/**
 * @export
 * @interface ProcessFeedResponse
 */
export interface ProcessFeedResponse {
  /**
   * Request status.
   *
   * @memberof ProcessFeedResponse
   * @type {string}
   */
  status?: string;
  /**
   * The number of received and accepted items.
   *
   * @memberof ProcessFeedResponse
   * @type {number}
   */
  acceptedCount?: number;
}
/**
 * @export
 * @interface ProductAttribute
 */
export interface ProductAttribute {
  /**
   * Product Attribute Code
   *
   * @memberof ProductAttribute
   * @type {string}
   */
  code: string;
  /**
   * A list of value(s) associated with a specified attribute code.
   *
   * @memberof ProductAttribute
   * @type {string[]}
   */
  values: string[];
  /**
   * The variant reference ID establishes a link between a product variant and the corresponding [Option Value
   * ID](#operation/createProducts!path=options/values/id&t=request) in a configurable product. A variant reference ID
   * can be specified only for a product that represents a variant of a configurable product.
   *
   * @memberof ProductAttribute
   * @type {string}
   */
  variantReferenceId?: string;
}
/**
 * @export
 * @interface ProductBundle
 */
export interface ProductBundle {
  /**
   * Name of the group that organizes the bundle items. This helps in categorizing the items within the bundle for
   * better organization. For example, groups can be "shirts", "pants", "accessories", etc.
   *
   * @memberof ProductBundle
   * @type {string}
   */
  group: string;
  /**
   * Indicates whether a shopper is required to select any products from this group to add the bundle to the shopping
   * cart.
   *
   * @memberof ProductBundle
   * @type {boolean}
   */
  required?: boolean;
  /**
   * Indicates whether multiple products can be selected by a shopper.
   *
   * @memberof ProductBundle
   * @type {boolean}
   */
  multiSelect?: boolean;
  /**
   * A list of default product SKUs that are selected in this bundle group.
   *
   * @memberof ProductBundle
   * @type {string[]}
   */
  defaultItemSkus?: string[];
  /**
   * A list of individual products that are part of the bundle. Each item in the list represents a product that can be
   * selected as part of the bundle.
   *
   * @memberof ProductBundle
   * @type {ProductBundleItem[]}
   */
  items: ProductBundleItem[];
}
/**
 * @export
 * @interface ProductBundleItem
 */
export interface ProductBundleItem {
  /**
   * Product SKU of the bundle item.
   *
   * @memberof ProductBundleItem
   * @type {string}
   */
  sku: string;
  /**
   * Quantity of the item in the bundle.
   *
   * @memberof ProductBundleItem
   * @type {number}
   */
  qty?: number;
  /**
   * Indicates whether the quantity of the item in the bundle can be defined by a shopper.
   *
   * @memberof ProductBundleItem
   * @type {boolean}
   */
  userDefinedQty?: boolean;
}
/**
 * @export
 * @interface ProductConfiguration
 */
export interface ProductConfiguration {
  /**
   * Product option attribute code. For `CONFIGURABLE` or `SWATCH` option types, this ID must match the ["attribute
   * code"](#operation/createProducts!path=attributes/code&t=request) used for the configurable product (for example,
   * "color").
   *
   * @memberof ProductConfiguration
   * @type {string}
   */
  attributeCode: string;
  /**
   * Option label
   *
   * @memberof ProductConfiguration
   * @type {string}
   */
  label?: string;
  /**
   * Specifies the pre-selected value variant reference id of the current option.
   *
   * @memberof ProductConfiguration
   * @type {string}
   */
  defaultVariantReferenceId?: string;
  /**
   * Option type. Indicates the product type the option can be assigned to. - `CONFIGURABLE`: Configurable product
   * option - `SWATCH`: Swatch product option. Must be used for color or text swatches attributes
   *
   * @memberof ProductConfiguration
   * @type {ProductConfigurationTypeEnum}
   */
  type: ProductConfigurationTypeEnum;
  /**
   * A list of option values. Defines option values available to shoppers (for example, "red" color or "large" size).
   *
   * @memberof ProductConfiguration
   * @type {ProductOptionValue[]}
   */
  values: ProductOptionValue[];
}
/**
 * @export
 * @interface ProductExternalId
 */
export interface ProductExternalId {
  /**
   * External ID of the product.
   *
   * @memberof ProductExternalId
   * @type {string}
   */
  id: string;
  /**
   * External ID origin. Specifies the system that generated the external ID, such as Adobe Commerce, Google Product
   * Ratings, etc.
   *
   * @memberof ProductExternalId
   * @type {string}
   */
  origin: string;
}
/**
 * @export
 * @interface ProductImage
 */
export interface ProductImage {
  /**
   * Media resource URL
   *
   * @memberof ProductImage
   * @type {string}
   */
  url: string;
  /**
   * Media resource label
   *
   * @memberof ProductImage
   * @type {string}
   */
  label?: string;
  /**
   * Roles associated with this image that determine how the image is used on the storefront. - `BASE`: Product image is
   * visible as a main image on the Product Detail Page. - `SMALL`: Product image is visible as a main image on the
   * Category or search result page or other product listing pages. - `THUMBNAIL`: Thumbnail images appear in the
   * thumbnail gallery, shopping cart, etc. - `SWATCH`: A swatch can be used to illustrate the color, pattern, or
   * texture.
   *
   * @memberof ProductImage
   * @type {ProductImageRolesEnum[]}
   */
  roles?: ProductImageRolesEnum[];
  /**
   * Custom image role. Merchants can define custom roles in addition to the predefined values.
   *
   * @memberof ProductImage
   * @type {string[]}
   */
  customRoles?: string[];
}
/**
 * Product association
 *
 * @export
 * @interface ProductLink
 */
export interface ProductLink {
  /**
   * Product link type. Merchants can define custom types in addition to the predefined values. - `VARIANT_OF` link type
   * must be specified to establish a connection to the configurable product SKU. - `IN_BUNDLE` link type must be
   * specified to establish a connection to the bundle product SKU.
   *
   * @memberof ProductLink
   * @type {string}
   */
  type: string;
  /**
   * Product SKU
   *
   * @memberof ProductLink
   * @type {string}
   */
  sku: string;
}
/**
 * Meta attributes that are specified in <meta> tags.
 *
 * @export
 * @interface ProductMetaAttribute
 */
export interface ProductMetaAttribute {
  /**
   * A meta title
   *
   * @memberof ProductMetaAttribute
   * @type {string}
   */
  title?: string;
  /**
   * A meta keywords
   *
   * @memberof ProductMetaAttribute
   * @type {string[]}
   */
  keywords?: string[];
  /**
   * A meta description
   *
   * @memberof ProductMetaAttribute
   * @type {string}
   */
  description?: string;
}
/**
 * @export
 * @interface ProductOptionValue
 */
export interface ProductOptionValue {
  /**
   * Option value ID. For `CONFIGURABLE` or `SWATCH` option types, this ID must match the
   * ["variantReferenceId"](#operation/createProducts!path=attributes/variantReferenceId&t=request) defined in the
   * product variant.
   *
   * @memberof ProductOptionValue
   * @type {string}
   */
  variantReferenceId: string;
  /**
   * Option value label
   *
   * @memberof ProductOptionValue
   * @type {string}
   */
  label?: string;
  /**
   * A hex representation of the color of the option value. Can be used for option with a SWATCH type.
   *
   * @memberof ProductOptionValue
   * @type {string}
   */
  colorHex?: string;
  /**
   * Image URL of the option value. Can be used for option with a SWATCH type.
   *
   * @memberof ProductOptionValue
   * @type {string}
   */
  imageUrl?: string;
}
/**
 * @export
 * @interface ProductRoutes
 */
export interface ProductRoutes {
  /**
   * URL path
   *
   * @memberof ProductRoutes
   * @type {string}
   */
  path: string;
  /**
   * Position of a product in the URL path. The default value is 0.
   *
   * @memberof ProductRoutes
   * @type {number}
   */
  position?: number;
}
/**
 * Source of the entity, for example, "en-US" for US English.
 *
 * @export
 * @interface Source
 */
export interface Source {
  /**
   * A single value that represents content locale, for example, English.
   *
   * @memberof Source
   * @type {string}
   */
  locale: string;
}
/**
 * Identifies the source context for a product layer, combining locale and layer name to create a unique layer
 * identifier. This allows for precise targeting of content overrides.
 *
 * @export
 * @interface SourceLayer
 */
export interface SourceLayer {
  /**
   * ISO locale code (for example, "en-US", "fr-FR", "de-DE") that specifies the target market or language. When
   * omitted, the layer applies globally across all locales. Use for market-specific customizations.
   *
   * @memberof SourceLayer
   * @type {string}
   */
  locale?: string;
  /**
   * Unique identifier for the layer within the product's layer hierarchy. Use descriptive names that indicate the
   * layer's purpose (for example, "seasonal-winter-2024", "promotional-black-friday", "a-b-test-variant").
   *
   * @memberof SourceLayer
   * @type {string}
   */
  layer: string;
}
/**
 * Final price offered for bulk purchases at a specific quantity threshold. Example: $100 regular price with tier price
 * of $80 for quantity of 5 or more.
 *
 * @export
 * @interface TierFinalPrice
 */
export interface TierFinalPrice {
  /**
   * Minimum quantity required to qualify for this tier price. Must be greater than 1.
   *
   * @memberof TierFinalPrice
   * @type {number}
   */
  qty: number;
  /**
   * Fixed price offered for the specified quantity threshold. Must be a positive number less than or equal to the
   * regular price.
   *
   * @memberof TierFinalPrice
   * @type {number}
   */
  price: number;
}
/**
 * Percentage discount applied to the regular price when purchasing at or above a specific quantity threshold. Example:
 * $100 regular price with 20% discount for quantity of 10 or more.
 *
 * @export
 * @interface TierPercentage
 */
export interface TierPercentage {
  /**
   * Minimum quantity required to qualify for this tier discount. Must be greater than 1.
   *
   * @memberof TierPercentage
   * @type {number}
   */
  qty: number;
  /**
   * Discount percentage applied to the specified quantity threshold. Valid range is 0.01 to 99.99 (1% to 99.99%).
   *
   * @memberof TierPercentage
   * @type {number}
   */
  percentage: number;
}

// Manually define any enum types that are referenced but not generated
/**
 * Enum for FeedMetadata.visibleIn
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataVisibleInEnum {
  ProductDetail = 'PRODUCT_DETAIL',
  ProductListing = 'PRODUCT_LISTING',
  SearchResults = 'SEARCH_RESULTS',
  ProductCompare = 'PRODUCT_COMPARE',
}
/**
 * Enum for FeedMetadata.dataType
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataDataTypeEnum {
  Text = 'TEXT',
  Decimal = 'DECIMAL',
  Integer = 'INTEGER',
  Boolean = 'BOOLEAN',
}
/**
 * Enum for FeedMetadata.searchTypes
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataSearchTypesEnum {
  Autocomplete = 'AUTOCOMPLETE',
  Contains = 'CONTAINS',
  StartsWith = 'STARTS_WITH',
}
/**
 * Enum for FeedMetadataUpdate.visibleIn
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataUpdateVisibleInEnum {
  ProductDetail = 'PRODUCT_DETAIL',
  ProductListing = 'PRODUCT_LISTING',
  SearchResults = 'SEARCH_RESULTS',
  ProductCompare = 'PRODUCT_COMPARE',
}
/**
 * Enum for FeedMetadataUpdate.dataType
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataUpdateDataTypeEnum {
  Text = 'TEXT',
  Decimal = 'DECIMAL',
  Integer = 'INTEGER',
  Boolean = 'BOOLEAN',
}
/**
 * Enum for FeedMetadataUpdate.searchTypes
 *
 * @export
 * @enum {string}
 */
export enum FeedMetadataUpdateSearchTypesEnum {
  Autocomplete = 'AUTOCOMPLETE',
  Contains = 'CONTAINS',
  StartsWith = 'STARTS_WITH',
}
/**
 * Enum for FeedProduct.status
 *
 * @export
 * @enum {string}
 */
export enum FeedProductStatusEnum {
  Enabled = 'ENABLED',
  Disabled = 'DISABLED',
}
/**
 * Enum for FeedProduct.visibleIn
 *
 * @export
 * @enum {string}
 */
export enum FeedProductVisibleInEnum {
  Catalog = 'CATALOG',
  Search = 'SEARCH',
}
/**
 * Enum for FeedProductUpdate.status
 *
 * @export
 * @enum {string}
 */
export enum FeedProductUpdateStatusEnum {
  Enabled = 'ENABLED',
  Disabled = 'DISABLED',
}
/**
 * Enum for FeedProductUpdate.visibleIn
 *
 * @export
 * @enum {string}
 */
export enum FeedProductUpdateVisibleInEnum {
  Catalog = 'CATALOG',
  Search = 'SEARCH',
}
/**
 * Enum for ProductConfiguration.type
 *
 * @export
 * @enum {string}
 */
export enum ProductConfigurationTypeEnum {
  Configurable = 'CONFIGURABLE',
  Swatch = 'SWATCH',
}
/**
 * Enum for ProductImage.roles
 *
 * @export
 * @enum {string}
 */
export enum ProductImageRolesEnum {
  Base = 'BASE',
  Small = 'SMALL',
  Thumbnail = 'THUMBNAIL',
  Swatch = 'SWATCH',
}

/**
 * Adobe IMS credentials
 *
 * @param clientId - The client ID for the API requests
 * @param clientSecret - The client secret for the API requests
 */
export interface AdobeCredentials {
  clientId: string;
  clientSecret: string;
}

export type Region = 'na1';

export type Environment = 'production' | 'sandbox';

/**
 * Client configuration
 *
 * @param credentials - Adobe IMS credentials for authentication
 * @param tenantId - The tenant ID for the API requests
 * @param region - The region for the API endpoint (e.g., 'us', 'eu')
 * @param environment - The environment to use ('production' or 'sandbox')
 * @param timeoutMs - The timeout for the API requests. Default is 10000ms.
 * @param logger - Optional logger for customizing logging behavior. Default is consoleLogger(LogLevel.INFO).
 */
export interface ClientConfig {
  credentials: AdobeCredentials;
  tenantId: string;
  region: Region;
  environment: Environment;
  timeoutMs?: number;
  logger?: Logger;
}

/**
 * API response
 *
 * @param ok - Whether the request was successful
 * @param status - The status code of the response
 * @param statusText - The status text of the response
 * @param data - The processed feed response data
 */
export interface ApiResponse {
  ok: boolean;
  status: number;
  statusText: string;
  data: ProcessFeedResponse;
}

/**
 * Logger interface for customizing logging behavior
 *
 * @param debug - Log a debug message
 * @param info - Log an info message
 * @param warn - Log a warning message
 * @param error - Log an error message
 */
export interface Logger {
  debug(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  error(message: string, error?: Error, ...args: unknown[]): void;
}

/**
 * Log level
 *
 * @param DEBUG - Debug log level
 * @param INFO - Info log level
 * @param WARN - Warning log level
 * @param ERROR - Error log level
 */
export enum LogLevel {
  DEBUG = 0,
  INFO = 1,
  WARN = 2,
  ERROR = 3,
}
