/**
 * Copyright 2025 Adobe. All Rights Reserved.
 *
 * This file is licensed to you under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, either express or implied. See the License for
 * the specific language governing permissions and limitations under the License.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) using custom templates.
 * Generator configuration can be found in the /generator directory.
 *
 * Do not edit this file manually!
 */

import { config } from 'dotenv';
import { describe, test, beforeAll, expect } from 'vitest';
import { Client, createClient } from '../../src/client';
import {
  FeedProduct,
  FeedProductStatusEnum,
  FeedProductVisibleInEnum,
  ProductAttributeTypeEnum,
  FeedProductUpdate,
  Environment,
  Region,
  ClientConfig,
  LogLevel,
} from '../../src/types';
import { consoleLogger } from '../../src/logger';

config();

const requiredEnvVars = ['IMS_CLIENT_ID', 'IMS_CLIENT_SECRET', 'TENANT_ID', 'REGION', 'ENVIRONMENT'];

for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    throw new Error(`Missing required environment variable: ${envVar}`);
  }
}

describe('Products Integration Tests', () => {
  let client: Client;

  const product1: FeedProduct = {
    sku: 'EXAMPLE-SKU-001',
    scope: { locale: 'en-US' },
    name: 'Example Product 1',
    slug: 'example-product-1',
    description: 'This is an example product created via the SDK',
    status: FeedProductStatusEnum.Enabled,
    visibleIn: [FeedProductVisibleInEnum.Catalog, FeedProductVisibleInEnum.Search],
    attributes: [
      {
        code: 'brand',
        type: ProductAttributeTypeEnum.String,
        values: ['Example Brand'],
      },
      {
        code: 'category',
        type: ProductAttributeTypeEnum.String,
        values: ['Electronics'],
      },
    ],
  };

  const product2: FeedProduct = {
    sku: 'EXAMPLE-SKU-002',
    scope: { locale: 'en-US' },
    name: 'Example Product 2',
    slug: 'example-product-2',
    description: 'This is another example product created via the SDK',
    status: FeedProductStatusEnum.Enabled,
    visibleIn: [FeedProductVisibleInEnum.Catalog, FeedProductVisibleInEnum.Search],
    attributes: [
      {
        code: 'brand',
        type: ProductAttributeTypeEnum.String,
        values: ['Example Brand'],
      },
      {
        code: 'category',
        type: ProductAttributeTypeEnum.String,
        values: ['Electronics'],
      },
    ],
  };

  beforeAll(() => {
    const config: ClientConfig = {
      credentials: {
        clientId: process.env.IMS_CLIENT_ID!,
        clientSecret: process.env.IMS_CLIENT_SECRET!,
      },
      tenantId: process.env.TENANT_ID!,
      region: process.env.REGION as Region,
      environment: process.env.ENVIRONMENT as Environment,
      logger: consoleLogger(LogLevel.DEBUG),
    };

    client = createClient(config);
  });

  test('should create products', async () => {
    const response = await client.createProducts([product1, product2]);
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.status).toBe(200);
    expect(response.statusText).toBe('OK');
    expect(response.data.status).toBe('ACCEPTED');
    expect(response.data.acceptedCount).toBe(2);
  });

  test('should update products', async () => {
    const productUpdate1: FeedProductUpdate = {
      sku: 'EXAMPLE-SKU-001',
      scope: { locale: 'en-US' },
      name: 'Updated Product Name',
    };

    const productUpdate2: FeedProductUpdate = {
      sku: 'EXAMPLE-SKU-002',
      scope: { locale: 'en-US' },
      name: 'Updated Product Name 2',
    };

    const response = await client.updateProducts([productUpdate1, productUpdate2]);
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.status).toBe(200);
    expect(response.statusText).toBe('OK');
    expect(response.data.status).toBe('ACCEPTED');
    expect(response.data.acceptedCount).toBe(2);
  });

  test('should delete products', async () => {
    const response = await client.deleteProducts([
      { sku: product1.sku, scope: product1.scope },
      { sku: product2.sku, scope: product2.scope },
    ]);
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.status).toBe(200);
    expect(response.statusText).toBe('OK');
    expect(response.data.status).toBe('ACCEPTED');
    expect(response.data.acceptedCount).toBe(2);
  });
});
