/**
 * Copyright 2025 Adobe. All Rights Reserved.
 *
 * This file is licensed to you under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, either express or implied. See the License for
 * the specific language governing permissions and limitations under the License.
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) using custom templates.
 * Generator configuration can be found in the /generator directory.
 *
 * Do not edit this file manually!
 */

import { config } from 'dotenv';
import { describe, beforeAll, expect, test } from 'vitest';
import { Client, createClient } from '../../src/client';
import {
  Environment,
  Region,
  ClientConfig,
  LogLevel,
  FeedProduct,
  FeedProductLayer,
  FeedProductStatusEnum,
  FeedProductVisibleInEnum,
} from '../../src/types';
import { consoleLogger } from '../../src/logger';

config();

const requiredEnvVars = ['IMS_CLIENT_ID', 'IMS_CLIENT_SECRET', 'TENANT_ID', 'REGION', 'ENVIRONMENT'];

for (const envVar of requiredEnvVars) {
  if (!process.env[envVar]) {
    throw new Error(`Missing required environment variable: ${envVar}`);
  }
}

describe('Product Layers Integration Tests', () => {
  let client: Client;

  const baseProduct: FeedProduct = {
    sku: 'BASE-SKU-001',
    source: { locale: 'en-US' },
    name: 'Product 1',
    slug: 'product-1',
    description: 'This is a the base product for the layer test',
    status: FeedProductStatusEnum.Enabled,
    visibleIn: [FeedProductVisibleInEnum.Catalog, FeedProductVisibleInEnum.Search],
    attributes: [
      {
        code: 'brand',
        values: ['Example Brand'],
      },
      {
        code: 'category',
        values: ['Electronics'],
      },
    ],
  };

  const productLayer: FeedProductLayer = {
    sku: 'BASE-SKU-001',
    source: { locale: 'en-US', layer: 'test-product-layer' },
    name: 'Product 1 - Layer 1',
    description: 'This is a different description for the base product',
    attributes: [
      {
        code: 'color',
        values: ['Yellow'],
      },
    ],
  };

  beforeAll(() => {
    const config: ClientConfig = {
      credentials: {
        clientId: process.env.IMS_CLIENT_ID!,
        clientSecret: process.env.IMS_CLIENT_SECRET!,
      },
      tenantId: process.env.TENANT_ID!,
      region: process.env.REGION as Region,
      environment: process.env.ENVIRONMENT as Environment,
      logger: consoleLogger(LogLevel.DEBUG),
    };

    client = createClient(config);
  });

  test('should create base product and product layer', async () => {
    const response = await client.createProducts([baseProduct]);
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.status).toBe(200);
    expect(response.statusText).toBe('OK');
    expect(response.data.status).toBe('ACCEPTED');
    expect(response.data.acceptedCount).toBe(1);

    const layerResponse = await client.createProductLayers([productLayer]);
    expect(layerResponse).toBeDefined();
    expect(layerResponse.ok).toBe(true);
    expect(layerResponse.status).toBe(200);
    expect(layerResponse.statusText).toBe('OK');
    expect(layerResponse.data.status).toBe('ACCEPTED');
    expect(layerResponse.data.acceptedCount).toBe(1);
  });

  test('should delete product layer and base product', async () => {
    const response = await client.deleteProductLayers([
      { sku: 'BASE-SKU-001', source: { locale: 'en-US', layer: 'test-product-layer' } },
    ]);
    expect(response).toBeDefined();
    expect(response.ok).toBe(true);
    expect(response.status).toBe(200);
    expect(response.statusText).toBe('OK');
    expect(response.data.status).toBe('ACCEPTED');
    expect(response.data.acceptedCount).toBe(1);

    const baseResponse = await client.deleteProducts([{ sku: 'BASE-SKU-001', source: { locale: 'en-US' } }]);
    expect(baseResponse).toBeDefined();
    expect(baseResponse.ok).toBe(true);
    expect(baseResponse.status).toBe(200);
    expect(baseResponse.statusText).toBe('OK');
    expect(baseResponse.data.status).toBe('ACCEPTED');
    expect(baseResponse.data.acceptedCount).toBe(1);
  });
});
